/* 
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Currency.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Currency.Model
{
    /// <summary>
    /// Result of performing an enumerate currencies operation
    /// </summary>
    [DataContract]
    public partial class AvailableCurrencyResponse :  IEquatable<AvailableCurrencyResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AvailableCurrencyResponse" /> class.
        /// </summary>
        /// <param name="currencies">List of available currencies from the API.</param>
        public AvailableCurrencyResponse(List<AvailableCurrency> currencies = default(List<AvailableCurrency>))
        {
            this.Currencies = currencies;
        }
        
        /// <summary>
        /// List of available currencies from the API
        /// </summary>
        /// <value>List of available currencies from the API</value>
        [DataMember(Name="Currencies", EmitDefaultValue=false)]
        public List<AvailableCurrency> Currencies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AvailableCurrencyResponse {\n");
            sb.Append("  Currencies: ").Append(Currencies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AvailableCurrencyResponse);
        }

        /// <summary>
        /// Returns true if AvailableCurrencyResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AvailableCurrencyResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AvailableCurrencyResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Currencies == input.Currencies ||
                    this.Currencies != null &&
                    this.Currencies.SequenceEqual(input.Currencies)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Currencies != null)
                    hashCode = hashCode * 59 + this.Currencies.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
