/* 
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Currency.Api;
using Cloudmersive.APIClient.NET.Currency.Model;
using Cloudmersive.APIClient.NET.Currency.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Currency.Test
{
    /// <summary>
    ///  Class for testing AvailableCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AvailableCurrencyTests
    {
        // TODO uncomment below to declare an instance variable for AvailableCurrency
        //private AvailableCurrency instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailableCurrency
            //instance = new AvailableCurrency();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailableCurrency
        /// </summary>
        [Test]
        public void AvailableCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AvailableCurrency
            //Assert.IsInstanceOfType<AvailableCurrency> (instance, "variable 'instance' is a AvailableCurrency");
        }


        /// <summary>
        /// Test the property 'ISOCurrencyCode'
        /// </summary>
        [Test]
        public void ISOCurrencyCodeTest()
        {
            // TODO unit test for the property 'ISOCurrencyCode'
        }
        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Test]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }
        /// <summary>
        /// Test the property 'CurrencyEnglishName'
        /// </summary>
        [Test]
        public void CurrencyEnglishNameTest()
        {
            // TODO unit test for the property 'CurrencyEnglishName'
        }
        /// <summary>
        /// Test the property 'CountryName'
        /// </summary>
        [Test]
        public void CountryNameTest()
        {
            // TODO unit test for the property 'CountryName'
        }
        /// <summary>
        /// Test the property 'CountryThreeLetterCode'
        /// </summary>
        [Test]
        public void CountryThreeLetterCodeTest()
        {
            // TODO unit test for the property 'CountryThreeLetterCode'
        }
        /// <summary>
        /// Test the property 'CountryISOTwoLetterCode'
        /// </summary>
        [Test]
        public void CountryISOTwoLetterCodeTest()
        {
            // TODO unit test for the property 'CountryISOTwoLetterCode'
        }
        /// <summary>
        /// Test the property 'IsEuropeanUnionMember'
        /// </summary>
        [Test]
        public void IsEuropeanUnionMemberTest()
        {
            // TODO unit test for the property 'IsEuropeanUnionMember'
        }

    }

}
