/* 
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Currency.Api;
using Cloudmersive.APIClient.NET.Currency.Model;
using Cloudmersive.APIClient.NET.Currency.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Currency.Test
{
    /// <summary>
    ///  Class for testing AvailableCurrencyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AvailableCurrencyResponseTests
    {
        // TODO uncomment below to declare an instance variable for AvailableCurrencyResponse
        //private AvailableCurrencyResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailableCurrencyResponse
            //instance = new AvailableCurrencyResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailableCurrencyResponse
        /// </summary>
        [Test]
        public void AvailableCurrencyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AvailableCurrencyResponse
            //Assert.IsInstanceOfType<AvailableCurrencyResponse> (instance, "variable 'instance' is a AvailableCurrencyResponse");
        }


        /// <summary>
        /// Test the property 'Currencies'
        /// </summary>
        [Test]
        public void CurrenciesTest()
        {
            // TODO unit test for the property 'Currencies'
        }

    }

}
