/* 
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Currency.Api;
using Cloudmersive.APIClient.NET.Currency.Model;
using Cloudmersive.APIClient.NET.Currency.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Currency.Test
{
    /// <summary>
    ///  Class for testing ConvertedCurrencyResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConvertedCurrencyResultTests
    {
        // TODO uncomment below to declare an instance variable for ConvertedCurrencyResult
        //private ConvertedCurrencyResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConvertedCurrencyResult
            //instance = new ConvertedCurrencyResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConvertedCurrencyResult
        /// </summary>
        [Test]
        public void ConvertedCurrencyResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConvertedCurrencyResult
            //Assert.IsInstanceOfType<ConvertedCurrencyResult> (instance, "variable 'instance' is a ConvertedCurrencyResult");
        }


        /// <summary>
        /// Test the property 'ConvertedPrice'
        /// </summary>
        [Test]
        public void ConvertedPriceTest()
        {
            // TODO unit test for the property 'ConvertedPrice'
        }
        /// <summary>
        /// Test the property 'ISOCurrencyCode'
        /// </summary>
        [Test]
        public void ISOCurrencyCodeTest()
        {
            // TODO unit test for the property 'ISOCurrencyCode'
        }
        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Test]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }
        /// <summary>
        /// Test the property 'FormattedPriceAsString'
        /// </summary>
        [Test]
        public void FormattedPriceAsStringTest()
        {
            // TODO unit test for the property 'FormattedPriceAsString'
        }

    }

}
