/* 
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Currency.Api;
using Cloudmersive.APIClient.NET.Currency.Model;
using Cloudmersive.APIClient.NET.Currency.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Currency.Test
{
    /// <summary>
    ///  Class for testing ExchangeRateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExchangeRateResultTests
    {
        // TODO uncomment below to declare an instance variable for ExchangeRateResult
        //private ExchangeRateResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExchangeRateResult
            //instance = new ExchangeRateResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExchangeRateResult
        /// </summary>
        [Test]
        public void ExchangeRateResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExchangeRateResult
            //Assert.IsInstanceOfType<ExchangeRateResult> (instance, "variable 'instance' is a ExchangeRateResult");
        }


        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }

    }

}
